name: Pull Request CI SHiELD idealized tests with intel21

on: [pull_request, workflow_dispatch]
jobs:
   Compile:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Compile SHiELD_solo
        #run: python3 /home/Lauren.Chilutti/pw/storage/PWscripts/FV3compileStartClusters.py $GITHUB_REF
        run: python3 /home/Lauren.Chilutti/pw/storage/PWscripts/FV3compileStartClusters.py
   #Tests:
    #runs-on: [self-hosted, Linux, X64]
    #needs: [Compile]
    #strategy:
      #max-parallel: 2
      #matrix:
      #  test: [C128r20.solo.superC, C128r3.solo.TC, d96_2k.solo.bubble, C96.sw.modon]
    #steps:
    #  - name: Run Test
    #    run: python3 /home/Lauren.Chilutti/pw/storage/PWscripts/FV3${{ matrix.test }}StartCLusters.py $GITHUB_REF
   ShutDownCluster:
    runs-on: [self-hosted, Linux, X64]
    if: always()
    #needs: [Compile, Tests]
    needs:[Compile]
    steps:
      - name: Turn off cluster
        env:
          CLUSTER: ci_fv3
        run: python3 /home/Lauren.Chilutti/pw/storage/PWscripts/stopClusters.py $CLUSTER
